ETHNICS=[{'id':'1', 'n':"White Mediterranean"},
    {'id':'2', 'n':'White caucasian'},
    {'id':'3', 'n':'Black'},
    {'id':'4', 'n':'Oriental/Asian'},
    {'id':'5', 'n':'Amerindian'},
    {'id':'6', 'n':'Gypsy'},
    {'id':'7', 'n':'Arabica'},
    {'id':'8', 'n':'Hindu'},
    {'id':'9', 'n':'Australian indigenous'},
    {'id':'10', 'n':'Askenazi Jew'},
    {'id':'11', 'n':'Sephardic Jew'}]