db.getCollection('Syndrome').insert({"sid":1, "c": "1", "n":"1p36 microdeletion syndrome"});
db.getCollection('Syndrome').insert({"sid":2, "c": "1", "n":"1p36 microdeletion  (GABRD)"});
db.getCollection('Syndrome').insert({"sid":3, "c": "1", "n":"1p36 microduplication (GABRD)"});
db.getCollection('Syndrome').insert({"sid":4, "c": "1", "n":"1p34.1 microduplication"});
db.getCollection('Syndrome').insert({"sid":5, "c": "1", "n":"1p32.2 microdeletion"});
db.getCollection('Syndrome').insert({"sid":6, "c": "1", "n":"1p21.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":7, "c": "1", "n":"1q21.1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":8, "c": "1", "n":"1q21.1 microduplication"});
db.getCollection('Syndrome').insert({"sid":9, "c": "1", "n":"Thrombocytopenia-absent radius syndrome/TAR"});
db.getCollection('Syndrome').insert({"sid":10, "c": "1", "n":"1q21.1 deletion (GJA5)"});
db.getCollection('Syndrome').insert({"sid":11, "c": "1", "n":"1q21.1 duplication (GJA5)"});
db.getCollection('Syndrome').insert({"sid":12, "c": "1", "n":"1q24q25 microdeletion"});
db.getCollection('Syndrome').insert({"sid":13, "c": "1", "n":"1q24.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":14, "c": "1", "n":"Van der Woude syndrome/VWS1"});
db.getCollection('Syndrome').insert({"sid":15, "c": "1", "n":"1q41–42 microdeletion"});
db.getCollection('Syndrome').insert({"sid":16, "c": "1", "n":"Corpus callosum agenesis microdeletion"});
db.getCollection('Syndrome').insert({"sid":17, "c": "2", "n":"2p25.3 microduplication"});
db.getCollection('Syndrome').insert({"sid":18, "c": "2", "n":"Feingold syndrome/FS"});
db.getCollection('Syndrome').insert({"sid":19, "c": "2", "n":"Hypotonia-cystinuria syndrome/HCS"});
db.getCollection('Syndrome').insert({"sid":20, "c": "2", "n":"Holoprosencephaly 2/HPE2 (SIX3)"});
db.getCollection('Syndrome').insert({"sid":21, "c": "2", "n":"2p21 microduplication"});
db.getCollection('Syndrome').insert({"sid":22, "c": "2", "n":"NRXN1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":23, "c": "2", "n":"NRXN1 microduplication"});
db.getCollection('Syndrome').insert({"sid":24, "c": "2", "n":"2p15–16.1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":25, "c": "2", "n":"2p14-p15 microdeletion"});
db.getCollection('Syndrome').insert({"sid":26, "c": "2", "n":"2p11.2-p12 microdeletion"});
db.getCollection('Syndrome').insert({"sid":27, "c": "2", "n":"2q11.2 microdeletion (LMAN2L, ARID5A)"});
db.getCollection('Syndrome').insert({"sid":28, "c": "2", "n":"Mesomelic dysplasia/MMD"});
db.getCollection('Syndrome').insert({"sid":29, "c": "2", "n":"2q11.2q13 microdeletion (NCK2, FHL2)"});
db.getCollection('Syndrome').insert({"sid":30, "c": "2", "n":"2q11.2q13 microduplication (NCK2, FHL2)"});
db.getCollection('Syndrome').insert({"sid":31, "c": "2", "n":"Joubert syndrome"});
db.getCollection('Syndrome').insert({"sid":32, "c": "2", "n":"Nephronophthisis 1/NPHP1"});
db.getCollection('Syndrome').insert({"sid":33, "c": "2", "n":"2q11.2q13 microduplication"});
db.getCollection('Syndrome').insert({"sid":34, "c": "2", "n":"2q13 microdeletion"});
db.getCollection('Syndrome').insert({"sid":35, "c": "2", "n":"2q13 microduplication"});
db.getCollection('Syndrome').insert({"sid":36, "c": "2", "n":"Autism-dyslexia microdeletion 2q14.3"});
db.getCollection('Syndrome').insert({"sid":37, "c": "2", "n":"2q14.3 microduplication"});
db.getCollection('Syndrome').insert({"sid":38, "c": "2", "n":"Mowat–Wilson syndrome/MWS"});
db.getCollection('Syndrome').insert({"sid":39, "c": "2", "n":"2q23.1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":40, "c": "2", "n":"2q23.3q24.1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":41, "c": "2", "n":"2q24.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":42, "c": "2", "n":"Neonatal epilepsy microduplication"});
db.getCollection('Syndrome').insert({"sid":43, "c": "2", "n":"Split hand/foot malformation 5/SHFM5"});
db.getCollection('Syndrome').insert({"sid":44, "c": "2", "n":"Synpolydactyly 1/SPD1"});
db.getCollection('Syndrome').insert({"sid":45, "c": "2", "n":"2q31.1 microduplication"});
db.getCollection('Syndrome').insert({"sid":46, "c": "2", "n":"2q31.2-q32.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":47, "c": "2", "n":"2q33.1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":48, "c": "2", "n":"Brachydactyly-mental retardation syndrome/BDMR"});
db.getCollection('Syndrome').insert({"sid":49, "c": "3", "n":"Distal 3p deletion"});
db.getCollection('Syndrome').insert({"sid":50, "c": "3", "n":"Von Hippel Lindau disease/VHL"});
db.getCollection('Syndrome').insert({"sid":51, "c": "3", "n":"3p21.31 microdeletion"});
db.getCollection('Syndrome').insert({"sid":52, "c": "3", "n":"3p14.1p13 microdeletion"});
db.getCollection('Syndrome').insert({"sid":53, "c": "3", "n":"3p11.1p12.1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":54, "c": "3", "n":"Proximal 3q microdeletion syndrome "});
db.getCollection('Syndrome').insert({"sid":55, "c": "3", "n":"3q13.31 microdeletion"});
db.getCollection('Syndrome').insert({"sid":56, "c": "3", "n":"Blepharophimosis, ptosis, and epicanthus inversus syndrome/BPES"});
db.getCollection('Syndrome').insert({"sid":57, "c": "3", "n":"Dandy–Walker syndrome/DWS"});
db.getCollection('Syndrome').insert({"sid":58, "c": "3", "n":"3q27.3q29 microdeletion"});
db.getCollection('Syndrome').insert({"sid":59, "c": "3", "n":"Split-Hand/Foot Malformation 4/SHFM4"});
db.getCollection('Syndrome').insert({"sid":60, "c": "3", "n":"3q29 microdeletion"});
db.getCollection('Syndrome').insert({"sid":61, "c": "3", "n":"3q29 microduplication"});
db.getCollection('Syndrome').insert({"sid":62, "c": "4", "n":"Wolf–Hirschhorn syndrome/WHS"});
db.getCollection('Syndrome').insert({"sid":63, "c": "4", "n":"4p16.3 microduplication"});
db.getCollection('Syndrome').insert({"sid":64, "c": "4", "n":"4p16.1 microduplication"});
db.getCollection('Syndrome').insert({"sid":65, "c": "4", "n":"4p15.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":66, "c": "4", "n": " 4q21.21q21.22 microdeletion"});
db.getCollection('Syndrome').insert({"sid":67, "c": "4", "n": "4q21 microdeletion"});
db.getCollection('Syndrome').insert({"sid":68, "c": "4", "n": "4q21.2q21.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":69, "c": "4", "n": "Parkinson disease/PARK1"});
db.getCollection('Syndrome').insert({"sid":70, "c": "4", "n": "Rieger type 1/RIEG1"});
db.getCollection('Syndrome').insert({"sid":71, "c": "4", "n": "4q32.1-q32.2 Triple/Duplication syndrome"});
db.getCollection('Syndrome').insert({"sid":72, "c": "5", "n": "Cri–du-Chat syndrome/CdCS"});
db.getCollection('Syndrome').insert({"sid":73, "c": "5", "n": "Cornelia de Lange syndrome/CDLS"});
db.getCollection('Syndrome').insert({"sid":74, "c": "5", "n": "NIPBL microduplication"});
db.getCollection('Syndrome').insert({"sid":75, "c": "5", "n": "Spinal muscular atrophy/SMA"});
db.getCollection('Syndrome').insert({"sid":76, "c": "5", "n": "5q14.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":77, "c": "5", "n": "5q14.3-q15 microdeletion"});
db.getCollection('Syndrome').insert({"sid":78, "c": "5", "n": "Familial adenomatous polyposis/FAP"});
db.getCollection('Syndrome').insert({"sid":79, "c": "5", "n": "Adult-onset autosomal dominant leukodystrophy/ADLD"});
db.getCollection('Syndrome').insert({"sid":80, "c": "5", "n": "PITX1 microdeletion"});
db.getCollection('Syndrome').insert({"sid":81, "c": "5", "n": "5q31.3 microdeletion"});
db.getCollection('Syndrome').insert({"sid":82, "c": "5", "n": "Pseudo trisomy 13 syndrome"});
db.getCollection('Syndrome').insert({"sid":83, "c": "5", "n": "Microdeletion 5q35.1"});
db.getCollection('Syndrome').insert({"sid":84, "c": "5", "n": "Parietal foramina/PFM"});
db.getCollection('Syndrome').insert({"sid":85, "c": "5", "n": "Sotos syndrome"});
db.getCollection('Syndrome').insert({"sid":86, "c": "5", "n": "5q35 microduplication"});
db.getCollection('Syndrome').insert({"sid":87, "c": "6", "n": "6p microdeletion"});
db.getCollection('Syndrome').insert({"sid":88, "c": "6", "n": "6p22.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":89, "c": "6", "n": "Adrenal hyperplasia/AH"});
db.getCollection('Syndrome').insert({"sid":90, "c": "6", "n": "6p21.31  microdeletion"});
db.getCollection('Syndrome').insert({"sid":91, "c": "6", "n": "Cleidocranial dysplasia"});
db.getCollection('Syndrome').insert({"sid":92, "c": "6", "n": "6q13–14  microdeletion"});
db.getCollection('Syndrome').insert({"sid":93, "c": "6", "n": "Prader–Willi like"});
db.getCollection('Syndrome').insert({"sid":94, "c": "6", "n": "Transient neonatal diabetes mellitus 1/TNDM1"});
db.getCollection('Syndrome').insert({"sid":95, "c": "6", "n": "6q25.2-q25.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":96, "c": "6", "n": "PARK2 microdeletion"});
db.getCollection('Syndrome').insert({"sid":97, "c": "6", "n": "PARK2 microduplication"});
db.getCollection('Syndrome').insert({"sid":98, "c": "6", "n": "6q27  microdeletion (anosmia)"});
db.getCollection('Syndrome').insert({"sid":99, "c": "6", "n": "Chondroma/CHDM"});
db.getCollection('Syndrome').insert({"sid":100, "c": "7", "n": "Saethre–Chotzen syndrome/SCS"});
db.getCollection('Syndrome').insert({"sid":101, "c": "7", "n": "Greig cephalopolysyndactyly/GCPS"});
db.getCollection('Syndrome').insert({"sid":102, "c": "7", "n": "Williams–Beuren syndrome/WBS"});
db.getCollection('Syndrome').insert({"sid":103, "c": "7", "n": "7q11.23 microduplication (WBS region duplication)"});
db.getCollection('Syndrome').insert({"sid":104, "c": "7", "n": "WBS-distal deletion (RHBDD2, HIP1)"});
db.getCollection('Syndrome').insert({"sid":105, "c": "7", "n": "Split hand/foot malformation 1/SHFM1"});
db.getCollection('Syndrome').insert({"sid":106, "c": "7", "n": "7q22.1-q22.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":107, "c": "7", "n": "Autism/dyslexia microdeletion 7q31.1"});
db.getCollection('Syndrome').insert({"sid":108, "c": "7", "n": "Speech-language-disorder 1/SPCH1"});
db.getCollection('Syndrome').insert({"sid":109, "c": "7", "n": "Holoprosencephaly 3/HPE3 (SHH)"});
db.getCollection('Syndrome').insert({"sid":110, "c": "7", "n": "Triphalangeal thumb polysyndactyly syndrome/TPTS"});
db.getCollection('Syndrome').insert({"sid":111, "c": "7", "n": "Currarino syndrome/CS"});
db.getCollection('Syndrome').insert({"sid":112, "c": "8", "n": "8p23.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":113, "c": "8", "n": "8p23.1 microduplication"});
db.getCollection('Syndrome').insert({"sid":114, "c": "8", "n": "Kabuki syndrome"});
db.getCollection('Syndrome').insert({"sid":115, "c": "8", "n": "8p21.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":116, "c": "8", "n": "8p12p21  microdeletion"});
db.getCollection('Syndrome').insert({"sid":117, "c": "8", "n": "8q11.23 microduplication"});
db.getCollection('Syndrome').insert({"sid":118, "c": "8", "n": "CHARGE syndrome"});
db.getCollection('Syndrome').insert({"sid":119, "c": "8", "n": "8q12 microduplication"});
db.getCollection('Syndrome').insert({"sid":120, "c": "8", "n": "8q12.3q13.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":121, "c": "8", "n": "Mesomelia-synostoses syndrome/MSS"});
db.getCollection('Syndrome').insert({"sid":122, "c": "8", "n": "Branchiootorenal syndrome (EYA1)"});
db.getCollection('Syndrome').insert({"sid":123, "c": "8", "n": " 8q21.11  microdeletion"});
db.getCollection('Syndrome').insert({"sid":124, "c": "8", "n": "Nablus mask-like facial syndrome/NMLFS"});
db.getCollection('Syndrome').insert({"sid":125, "c": "8", "n": "8q22.2q22.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":126, "c": "8", "n": "Langer–Giedion syndrome/LGS; Trichorrhinophalangeal type I"});
db.getCollection('Syndrome').insert({"sid":127, "c": "9", "n": "Sex reversal syndrome 4/SRXY4"});
db.getCollection('Syndrome').insert({"sid":128, "c": "9", "n": "Monosomy 9p syndrome"});
db.getCollection('Syndrome').insert({"sid":129, "c": "9", "n": "9q21.11 microduplication"});
db.getCollection('Syndrome').insert({"sid":130, "c": "9", "n": "9q22.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":131, "c": "9", "n": "PTCH1 microduplication"});
db.getCollection('Syndrome').insert({"sid":132, "c": "9", "n": "Holoprosencephaly 7/HPE7"});
db.getCollection('Syndrome').insert({"sid":133, "c": "9", "n": "Basal cell nevus syndrome (PTCH1)"});
db.getCollection('Syndrome').insert({"sid":134, "c": "9", "n": "Nail-patella syndrome/NPS"});
db.getCollection('Syndrome').insert({"sid":135, "c": "9", "n": "Early infantile epileptic encephalopathy 4/EIEE4"});
db.getCollection('Syndrome').insert({"sid":136, "c": "9", "n": "9q34 (EHMT1)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":137, "c": "9", "n": "9q34 (EHMT1) microduplication"});
db.getCollection('Syndrome').insert({"sid":138, "c": "9", "n": "Subtelomere deletion 9q"});
db.getCollection('Syndrome').insert({"sid":139, "c": "10", "n": "Hypoparathyroidism, sensorineural deafness, and renal disease/HDRS"});
db.getCollection('Syndrome').insert({"sid":140, "c": "10", "n": "Di George syndrome 2/DGS2"});
db.getCollection('Syndrome').insert({"sid":141, "c": "10", "n": "10q22-q23 (NRG3, GRID1)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":142, "c": "10", "n": "Juvenile polyposis syndrome/JPS"});
db.getCollection('Syndrome').insert({"sid":143, "c": "10", "n": "Split-Hand/Foot Malformation 3/SHFM3"});
db.getCollection('Syndrome').insert({"sid":144, "c": "10", "n": "10q25q26  microdeletion"});
db.getCollection('Syndrome').insert({"sid":145, "c": "11", "n": "Beckwith–Wiedemann syndrome/BWS—Silver Russell syndrome/SRS microdeletion"});
db.getCollection('Syndrome').insert({"sid":146, "c": "11", "n": "Beckwith–Wiedemann syndrome/BWS—Silver Russell syndrome/SRS microduplication"});
db.getCollection('Syndrome').insert({"sid":147, "c": "11", "n": "Wilms tumor syndrome (isolated)"});
db.getCollection('Syndrome').insert({"sid":148, "c": "11", "n": "WAGR syndrome"});
db.getCollection('Syndrome').insert({"sid":149, "c": "11", "n": "11p13 microduplication"});
db.getCollection('Syndrome').insert({"sid":150, "c": "11", "n": "Potocki–Shaffer syndrome/PSS"});
db.getCollection('Syndrome').insert({"sid":151, "c": "11", "n": "Spinocerebellar ataxia type 20/SCA20"});
db.getCollection('Syndrome').insert({"sid":152, "c": "11", "n": "11q14.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":153, "c": "11", "n": "Jacobsen syndrome/JBS"});
db.getCollection('Syndrome').insert({"sid":154, "c": "12", "n": "12p13.31 microduplication"});
db.getCollection('Syndrome').insert({"sid":155, "c": "12", "n": "12q14  microdeletion"});
db.getCollection('Syndrome').insert({"sid":156, "c": "12", "n": "Buschke-Ollendorff syndrome"});
db.getCollection('Syndrome').insert({"sid":157, "c": "12", "n": "Nasal speech-hypothyroidism microdeletion/NSH"});
db.getCollection('Syndrome').insert({"sid":158, "c": "12", "n": "Noonan syndrome 1/NS1"});
db.getCollection('Syndrome').insert({"sid":159, "c": "13", "n": "13q12 (CRYL1)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":160, "c": "13", "n": "13q12 (CRYL1) microduplication"});
db.getCollection('Syndrome').insert({"sid":161, "c": "13", "n": "Spastic ataxia Charlevoix–Saguenay/SACS"});
db.getCollection('Syndrome').insert({"sid":162, "c": "13", "n": "13q12.3-q13.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":163, "c": "13", "n": "Retinoblastoma/RB1"});
db.getCollection('Syndrome').insert({"sid":164, "c": "13", "n": "Hirschsprung disease 2/HSCR2"});
db.getCollection('Syndrome').insert({"sid":165, "c": "13", "n": "Holoprosencephaly5/HPE5 (ZIC2)"});
db.getCollection('Syndrome').insert({"sid":166, "c": "14", "n": "14q11.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":167, "c": "14", "n": "Congenital Rett variant/CRV"});
db.getCollection('Syndrome').insert({"sid":168, "c": "14", "n": "14q12 microduplication"});
db.getCollection('Syndrome').insert({"sid":169, "c": "14", "n": "14q22-q23  microdeletion"});
db.getCollection('Syndrome').insert({"sid":170, "c": "14", "n": "Autism spherocytosis microdeletion/ASC"});
db.getCollection('Syndrome').insert({"sid":171, "c": "14", "n": "14q32.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":172, "c": "15", "n": "15q11.2 (NIPA1)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":173, "c": "15", "n": "15q11.2 (NIPA1) microduplication"});
db.getCollection('Syndrome').insert({"sid":174, "c": "15", "n": "Angelman syndrome Typ1/AS1"});
db.getCollection('Syndrome').insert({"sid":175, "c": "15", "n": "Chromosome 15 microduplciation"});
db.getCollection('Syndrome').insert({"sid":176, "c": "15", "n": "Angelman syndrome Typ2/AS2"});
db.getCollection('Syndrome').insert({"sid":177, "c": "15", "n": "Prader–Willi syndrome Typ 1/ PWS1"});
db.getCollection('Syndrome').insert({"sid":178, "c": "15", "n": "Prader–Willi syndrome Typ 2/ PWS2"});
db.getCollection('Syndrome').insert({"sid":179, "c": "15", "n": "15q13.3 (CHRNA7)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":180, "c": "15", "n": "15q13.3 (CHRNA7) microduplication"});
db.getCollection('Syndrome').insert({"sid":181, "c": "15", "n": "15q14  microdeletion"});
db.getCollection('Syndrome').insert({"sid":182, "c": "15", "n": "Deafness and male infertility syndrome/DMIS"});
db.getCollection('Syndrome').insert({"sid":183, "c": "15", "n": "15q21  microdeletion"});
db.getCollection('Syndrome').insert({"sid":184, "c": "15", "n": "15q24 (BBS4,NPTN, NE01)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":185, "c": "15", "n": "15q24  microdeletion"});
db.getCollection('Syndrome').insert({"sid":186, "c": "15", "n": "15q24 microduplciation"});
db.getCollection('Syndrome').insert({"sid":187, "c": "15", "n": "Orofacial clefting/OC"});
db.getCollection('Syndrome').insert({"sid":188, "c": "15", "n": "15q25 microdeletion"});
db.getCollection('Syndrome').insert({"sid":189, "c": "15", "n": "15q26.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":190, "c": "15", "n": "Fryns syndrome/FNS"});
db.getCollection('Syndrome').insert({"sid":191, "c": "15", "n": "15q26.2-qter  microdeletion"});
db.getCollection('Syndrome').insert({"sid":192, "c": "16", "n": "ATR-16-syndrome"});
db.getCollection('Syndrome').insert({"sid":193, "c": "16", "n": "Tuberous sclerosis microdeletion syndrome/PKDTS"});
db.getCollection('Syndrome').insert({"sid":194, "c": "16", "n": "Tuberous sclerosis microduplication"});
db.getCollection('Syndrome').insert({"sid":195, "c": "16", "n": "Rubinstein–Taybi syndrome 1/RSTS1"});
db.getCollection('Syndrome').insert({"sid":196, "c": "16", "n": "Rubinstein–Taybi-microduplication"});
db.getCollection('Syndrome').insert({"sid":197, "c": "16", "n": "16p13.1 (MYH11)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":198, "c": "16", "n": "16p13.1 (MYH11) microduplication"});
db.getCollection('Syndrome').insert({"sid":199, "c": "16", "n": "16p11.2-p12.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":200, "c": "16", "n": "16p11.2-p12.2 microduplication"});
db.getCollection('Syndrome').insert({"sid":201, "c": "16", "n": "16p12.1 (EEF2K,CDR2)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":202, "c": "16", "n": "16p12.2 (EEF2K,CDR2) microduplication"});
db.getCollection('Syndrome').insert({"sid":203, "c": "16", "n": "16q11.2 distal microdeletion (SH2B1)"});
db.getCollection('Syndrome').insert({"sid":204, "c": "16", "n": "16q11.2 distal microduplication (SH2B1)"});
db.getCollection('Syndrome').insert({"sid":205, "c": "16", "n": "16p11.2 (TBX6)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":206, "c": "16", "n": "16p11.2 (TBX6) microduplication"});
db.getCollection('Syndrome').insert({"sid":207, "c": "16", "n": "16q11.2-q12.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":208, "c": "16", "n": "16q21-q22  microdeletion"});
db.getCollection('Syndrome').insert({"sid":209, "c": "16", "n": "16q12.1-q12.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":210, "c": "16", "n": "Townes-Brocks syndrome"});
db.getCollection('Syndrome').insert({"sid":211, "c": "16", "n": "16q24.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":212, "c": "16", "n": "FANCA deletion"});
db.getCollection('Syndrome').insert({"sid":213, "c": "17", "n": "Miller–Dieker syndrome/MDLS"});
db.getCollection('Syndrome').insert({"sid":214, "c": "17", "n": "Miller–Dieker microduplication"});
db.getCollection('Syndrome').insert({"sid":215, "c": "17", "n": "17p13.3 (YWHAE)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":216, "c": "17", "n": "17p13.3 (YWHAE) microduplication"});
db.getCollection('Syndrome').insert({"sid":217, "c": "17", "n": "17p13.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":218, "c": "17", "n": "Hereditary liability to pressure palsies/HNPP"});
db.getCollection('Syndrome').insert({"sid":219, "c": "17", "n": "Charcot–Marie–Tooth 1A/CMT1A"});
db.getCollection('Syndrome').insert({"sid":220, "c": "17", "n": "Smith–Magenis syndrome/SMS"});
db.getCollection('Syndrome').insert({"sid":221, "c": "17", "n": "Potocki–Lupski syndrome/PTLS"});
db.getCollection('Syndrome').insert({"sid":222, "c": "17", "n": "Neurofibromatosis 1/NF1"});
db.getCollection('Syndrome').insert({"sid":223, "c": "17", "n": "NF1 microduplication"});
db.getCollection('Syndrome').insert({"sid":224, "c": "17", "n": "17q11.2-q12  microdeletion"});
db.getCollection('Syndrome').insert({"sid":225, "c": "17", "n": "17q12a  microdeletion"});
db.getCollection('Syndrome').insert({"sid":226, "c": "17", "n": "Renal cysts and diabetes syndrome/RCAD"});
db.getCollection('Syndrome').insert({"sid":227, "c": "17", "n": "17q12b microduplication"});
db.getCollection('Syndrome').insert({"sid":228, "c": "17", "n": "Van Buchem disease/VBCH"});
db.getCollection('Syndrome').insert({"sid":229, "c": "17", "n": "17q21.31 (MAPT)  microdeletion"});
db.getCollection('Syndrome').insert({"sid":230, "c": "17", "n": "17q21.31 (MAPT) microduplication"});
db.getCollection('Syndrome').insert({"sid":231, "c": "17", "n": "17q21.31-q21.32  microdeletion"});
db.getCollection('Syndrome').insert({"sid":232, "c": "17", "n": "17q22-q23.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":233, "c": "17", "n": "17q23.1–23.2 microduplication"});
db.getCollection('Syndrome').insert({"sid":234, "c": "17", "n": "Camptomelic dysplasia"});
db.getCollection('Syndrome').insert({"sid":235, "c": "17", "n": "17q24.2-q24.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":236, "c": "17", "n": "Carney complex syndrome 1/CNC1"});
db.getCollection('Syndrome').insert({"sid":237, "c": "17", "n": "17q24.3 microduplication"});
db.getCollection('Syndrome').insert({"sid":238, "c": "18", "n": "Holoprosencephaly 4/HPE4 (TGIF1)"});
db.getCollection('Syndrome').insert({"sid":239, "c": "18", "n": "Proximal 18q microdeletion"});
db.getCollection('Syndrome').insert({"sid":240, "c": "18", "n": "Pitt–Hopkins syndrome/PTHS"});
db.getCollection('Syndrome').insert({"sid":241, "c": "18", "n": "18q22.3-q23  microdeletion"});
db.getCollection('Syndrome').insert({"sid":242, "c": "19", "n": "Sotos-like microduplication 19p13.2"});
db.getCollection('Syndrome').insert({"sid":243, "c": "19", "n": "19p13.13  microdeletion"});
db.getCollection('Syndrome').insert({"sid":244, "c": "19", "n": " 19p13.13 microduplication"});
db.getCollection('Syndrome').insert({"sid":245, "c": "19", "n": "19p13.12  microdeletion"});
db.getCollection('Syndrome').insert({"sid":246, "c": "19", "n": "19p13.11  microdeletion"});
db.getCollection('Syndrome').insert({"sid":247, "c": "19", "n": "19q13.11  microdeletion"});
db.getCollection('Syndrome').insert({"sid":248, "c": "19", "n": "Diamond–Blackfan anemia/DBA"});
db.getCollection('Syndrome').insert({"sid":249, "c": "20", "n": "20p12.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":250, "c": "20", "n": "Alagille syndrome 1/ALGS1"});
db.getCollection('Syndrome').insert({"sid":251, "c": "20", "n": "20q13.13-q13.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":252, "c": "20", "n": "Albright hereditary osteodystrophy/AHO"});
db.getCollection('Syndrome').insert({"sid":253, "c": "20", "n": "20q13.33  microdeletion"});
db.getCollection('Syndrome').insert({"sid":254, "c": "21", "n": "21q21.1  microdeletion"});
db.getCollection('Syndrome').insert({"sid":255, "c": "21", "n": "21q21.3  microdeletion"});
db.getCollection('Syndrome').insert({"sid":256, "c": "21", "n": "Platelet disorder/PD"});
db.getCollection('Syndrome').insert({"sid":257, "c": "21", "n": "Down syndrome/DS"});
db.getCollection('Syndrome').insert({"sid":258, "c": "21", "n": "Holoprosencephaly (TMEM1)"});
db.getCollection('Syndrome').insert({"sid":259, "c": "22", "n": "Cat-Eye syndrome/CES"});
db.getCollection('Syndrome').insert({"sid":260, "c": "22", "n": "Di George syndrome/CATCH22/DGS"});
db.getCollection('Syndrome').insert({"sid":261, "c": "22", "n": "22q11.2 microduplication"});
db.getCollection('Syndrome').insert({"sid":262, "c": "22", "n": "Distal microdeletion 22q11.2 (BCR, MAPK1)"});
db.getCollection('Syndrome').insert({"sid":263, "c": "22", "n": "Distal microduplication 22q11.2 (BCR, MAPK1)"});
db.getCollection('Syndrome').insert({"sid":264, "c": "22", "n": "Neurofibromatosis 2 microdeletion syndrome"});
db.getCollection('Syndrome').insert({"sid":265, "c": "22", "n": "Phelan–McDermid syndrome"});
db.getCollection('Syndrome').insert({"sid":266, "c": "X", "n": "22q13 (SHANK3) microduplication"});
db.getCollection('Syndrome').insert({"sid":267, "c": "X", "n": "Metachromatic Leukodystrophy"});
db.getCollection('Syndrome').insert({"sid":268, "c": "X", "n": "Leri–Weill dyschondrosteosis/LWD"});
db.getCollection('Syndrome').insert({"sid":269, "c": "X", "n": "X-Linked autism-2/AUTSX2"});
db.getCollection('Syndrome').insert({"sid":270, "c": "X", "n": "Steroid sulphatase deficiency/STS (Ichthyosis, X-linked)"});
db.getCollection('Syndrome').insert({"sid":271, "c": "X", "n": "Kallmann syndrome 1/KAL1"});
db.getCollection('Syndrome').insert({"sid":272, "c": "X", "n": "Microphthalmia syndromic type 7"});
db.getCollection('Syndrome').insert({"sid":273, "c": "X", "n": "MIDAS syndrome"});
db.getCollection('Syndrome').insert({"sid":274, "c": "X", "n": "Nance–Horan syndrome/NHS"});
db.getCollection('Syndrome').insert({"sid":275, "c": "X", "n": "Xp22.11  microdeletion"});
db.getCollection('Syndrome').insert({"sid":276, "c": "X", "n": "X-linked congenital adrenal hypoplasia/AHC"});
db.getCollection('Syndrome').insert({"sid":277, "c": "X", "n": "DAX1 microduplication"});
db.getCollection('Syndrome').insert({"sid":278, "c": "X", "n": "Complex glycerol kinase/CGK (Hyperglycerolemia)"});
db.getCollection('Syndrome').insert({"sid":279, "c": "X", "n": "Duchenne/Becker muscular dystrophy /DMD"});
db.getCollection('Syndrome').insert({"sid":280, "c": "X", "n": "Xp11.3 deletion syndrome"});
db.getCollection('Syndrome').insert({"sid":281, "c": "X", "n": "Goltz syndrome/GS"});
db.getCollection('Syndrome').insert({"sid":282, "c": "X", "n": "17-beta-hydroxysteroid dehydrogenase X/HSD"});
db.getCollection('Syndrome').insert({"sid":283, "c": "X", "n": "Xq12q13.1 microduplication"});
db.getCollection('Syndrome').insert({"sid":284, "c": "X", "n": "Charcot–Marie–Tooth X-linked/CMTX1"});
db.getCollection('Syndrome').insert({"sid":285, "c": "X", "n": "X inactivation specific transcript/XIST"});
db.getCollection('Syndrome').insert({"sid":286, "c": "X", "n": "Dosage-sensitive sex reversal"});
db.getCollection('Syndrome').insert({"sid":287, "c": "X", "n": "Bruton agammaglobulinemia/XLA"});
db.getCollection('Syndrome').insert({"sid":288, "c": "X", "n": "Xq22.2  microdeletion"});
db.getCollection('Syndrome').insert({"sid":289, "c": "X", "n": "Pelizaeus–Merzbacher microduplication/PMD"});
db.getCollection('Syndrome').insert({"sid":290, "c": "X", "n": "Lissencephaly, X-linked"});
db.getCollection('Syndrome').insert({"sid":291, "c": "X", "n": "Xq22.3q23  microdeletion"});
db.getCollection('Syndrome').insert({"sid":292, "c": "X", "n": "Lymphoproliferative syndrome 1/XLP1"});
db.getCollection('Syndrome').insert({"sid":293, "c": "X", "n": "Heterotaxia, visceral, 1, X-linked (HTX1; ZIC3)"});
db.getCollection('Syndrome').insert({"sid":294, "c": "X", "n": "X-linked hypopituitarism with intellectual disability/SRXX3"});
db.getCollection('Syndrome').insert({"sid":295, "c": "X", "n": "Fragile site mental retardation 1/FMR1"});
db.getCollection('Syndrome').insert({"sid":296, "c": "X", "n": "Xq28  microdeletion"});
db.getCollection('Syndrome').insert({"sid":297, "c": "X", "n": "Rett syndrome/RS"});
db.getCollection('Syndrome').insert({"sid":298, "c": "X", "n": "MECP2 microduplication"});
db.getCollection('Syndrome').insert({"sid":299, "c": "Y", "n": "Sex-determining region Y/SRY"});
db.getCollection('Syndrome').insert({"sid":300, "c": "Y", "n": "AZFa microdeletion"});
db.getCollection('Syndrome').insert({"sid":301, "c": "Y", "n": "AZFb microdeletion"});
db.getCollection('Syndrome').insert({"sid":302, "c": "Y", "n": "AZFb+c microdeletion"});
db.getCollection('Syndrome').insert({"sid":303, "c": "Y", "n": "AZFc microdeletion"});