SYNDROMES=[{'id':'1', 'n':"1p36 microdeletion syndrome"},
    {'id':'2', 'n':'1q21.1 susceptibility locus for Thrombocytopenia-Absent Radius (TAR) syndrome'}, 
    {'id':'3', 'n':'1q21.1 recurrent microdeletion (susceptibility locus for neurodevelopmental disorders)'},
    {'id':'4', 'n':'1q21.1 recurrent microduplication (possible susceptibility locus for neurodevelopmental disorders)'},
    {'id':'5', 'n':'2p21 Microdeletion Syndrome'},
    {'id':'6', 'n':'2p15-16.1 microdeletion syndrome'},
    {'id':'7', 'n':'2q33.1 deletion syndrome'},
    {'id':'8', 'n':'2q37 monosomy'},
    {'id':'9', 'n':'3q29 microdeletion syndrome'},
    {'id':'10', 'n':'3q29 microduplication syndrome'},
    {'id':'11', 'n':'Wolf-Hirschhorn Syndrome'},
    {'id':'12', 'n':'Cri du Chat Syndrome (5p deletion)'},
    {'id':'13', 'n':'Familial Adenomatous Polyposis'},
    {'id':'14', 'n':'Adult-onset autosomal dominant leukodystrophy (ADLD)'},
    {'id':'15', 'n':'Sotos syndrome'},
    {'id':'16', 'n':'Williams-Beuren Syndrome (WBS)'},
    {'id':'17', 'n':'7q11.23 duplication syndrome'},
    {'id':'18', 'n':'Split hand/foot malformation 1 (SHFM1) '},
    {'id':'19', 'n':'8p23.1 deletion syndrome'},
    {'id':'20', 'n':'8p23.1 duplication syndrome'},
    {'id':'21', 'n':'8q21.11 Microdeletion Syndrome'},
    {'id':'22', 'n':'9q subtelomeric deletion syndrome'},
    {'id':'23', 'n':'WAGR 11p13 deletion syndrome'},
    {'id':'24', 'n':'Potocki-Shaffer syndrome'},
    {'id':'25', 'n':'12p13.33 Microdeletion Syndrome'},
    {'id':'26', 'n':'12q14 microdeletion syndrome'},
    {'id':'27', 'n':'Prader-Willi syndrome (Type 1)'},
    {'id':'28', 'n':'Angelman syndrome (Type 1)'},
    {'id':'29', 'n':'Prader-Willi Syndrome (Type 2)'},
    {'id':'30', 'n':'Angelman syndrome (Type 2)'},
    {'id':'31', 'n':'15q13.3 microdeletion syndrome'},
    {'id':'32', 'n':'15q24 recurrent microdeletion syndrome'},
    {'id':'33', 'n':'15q26 overgrowth syndrome'},
    {'id':'34', 'n':'ATR-16 syndrome'},
    {'id':'35', 'n':'Rubinstein-Taybi Syndrome'},
    {'id':'36', 'n':'16p13.11 recurrent microdeletion (neurocognitive disorder susceptibility locus)'},
    {'id':'7', 'n':'16p13.11 recurrent microduplication (neurocognitive disorder susceptibility locus)'},
    {'id':'38', 'n':'16p11.2-p12.2 microduplication syndrome'},
    {'id':'39', 'n':'16p11.2-p12.2 microdeletion syndrome'},
    {'id':'40', 'n':'Recurrent 16p12.1 microdeletion (neurodevelopmental susceptibility locus)'},
    {'id':'41', 'n':'16p11.2 microduplication syndrome'},
    {'id':'42', 'n':'Miller-Dieker syndrome (MDS)'},
    {'id':'43', 'n':'Charcot-Marie-Tooth syndrome type 1A (CMT1A)'},
    {'id':'44', 'n':'Hereditary Liability to Pressure Palsies (HNPP)'},
    {'id':'45', 'n':'Smith-Magenis Syndrome'},
    {'id':'46', 'n':'Potocki-Lupski syndrome (17p11.2 duplication syndrome)'},
    {'id':'47', 'n':'NF1-microdeletion syndrome'},
    {'id':'48', 'n':'RCAD (renal cysts and diabetes)'},
    {'id':'49', 'n':'17q21.31 recurrent microdeletion syndrome (Koolen de Vries syndrome)'},
    {'id':'50', 'n':'Early-onset Alzheimer disease with cerebral amyloid angiopathy'},
    {'id':'51', 'n':'Cat-Eye Syndrome (Type I)'},
    {'id':'52', 'n':'22q11 deletion syndrome (Velocardiofacial / DiGeorge syndrome)'},
    {'id':'53', 'n':'22q11 duplication syndrome'},
    {'id':'54', 'n':'22q11.2 distal deletion syndrome'},
    {'id':'55', 'n':'22q13 deletion syndrome (Phelan-Mcdermid syndrome)'},
    {'id':'56', 'n':'Leri-Weill dyschondrostosis (LWD) - SHOX deletion'},
    {'id':'57', 'n':'Leri-Weill dyschondrostosis (LWD) - SHOX deletion'},
    {'id':'58', 'n':'Steroid sulphatase deficiency (STS)'},
    {'id':'59', 'n':'Xp11.22-p11.23 Microduplication'},
    {'id':'60', 'n':'Xp11.22-linked intellectual disability'},
    {'id':'61', 'n':'Pelizaeus-Merzbacher disease'},
    {'id':'62', 'n':'Xq28 (MECP2) duplication'},
    {'id':'63', 'n':'Xq28 Microduplication'},
    {'id':'64', 'n':'AZFa'},
    {'id':'65', 'n':'AZFb+AZFc'}]